name: Deploy to Server

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd polydl
            git reset --hard origin/stable
            git pull origin stable
            docker compose pull
            docker compose up -d --build --remove-orphans
            docker image prune -f
